# Generated by Django 3.2.3 on 2021-05-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('Product_Category', models.CharField(max_length=20)),
                ('Image_url', models.CharField(max_length=800)),
                ('Price', models.IntegerField()),
                ('SKU', models.CharField(max_length=20)),
                ('Slug', models.CharField(max_length=10)),
            ],
        ),
    ]
